### ISSUE TITLE
[기능 요청] 게시글 작성 페이지 완성

### ISSUE THREAD

**Issue by nnoonjy** [ApptiveDev/ygyg-fe#8]
## 💡 개요

미완성이었던 게시글 작성 페이지를 완성합니다.

## ✅ To-do

- [x] 이미지 첨부 필드
- [x] 최소최대 인원 선택 및 하위 필드
- [x] 날짜 및 시간 필드
